sudo: required
services:
  - docker

before_install:
  - docker build -t starnal/docker-react -f Dockerfile.dev .
script:
  - docker run starnal/docker-react npm run test -- --coverage  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-test"
  bucket_name: "elasticbeanstalk-us-east-2-178672148123"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"


